GET http://localhost:5086/data

###

POST http://localhost:5086/data
Content-Type: application/json

{
  "name": "Apfel",
  "name2": "Rot",
  "amount": 5,
  "amount2": 5
}

###

PUT http://localhost:5086/data/4
Content-Type: application/json

{
  "name": "Birne",
  "name2": "Gruen",
  "amount": 8,
  "amount2": 5
}

###

DELETE http://localhost:5086/data/9

###

GET http://localhost:5086/data/export